
export const countries=[
  { "name": "Afghanistan", "code": "AF", "alpha3": "AFG", "languages": ["Pashto", "Dari"] },
  { "name": "Åland Islands", "code": "AX", "alpha3": "ALA", "languages": ["Swedish"] },
  { "name": "Albania", "code": "AL", "alpha3": "ALB", "languages": ["Albanian"] },
  { "name": "Algeria", "code": "DZ", "alpha3": "DZA", "languages": ["Arabic", "Berber"] },
  { "name": "American Samoa", "code": "AS", "alpha3": "ASM", "languages": ["English", "Samoan"] },
  { "name": "Andorra", "code": "AD", "alpha3": "AND", "languages": ["Catalan"] },
  { "name": "Angola", "code": "AO", "alpha3": "AGO", "languages": ["Portuguese"] },
  { "name": "Anguilla", "code": "AI", "alpha3": "AIA", "languages": ["English"] },
  { "name": "Antarctica", "code": "AQ", "alpha3": "ATA", "languages": ["None"] },
  { "name": "Antigua and Barbuda", "code": "AG", "alpha3": "ATG", "languages": ["English"] },
  { "name": "Argentina", "code": "AR", "alpha3": "ARG", "languages": ["Spanish"] },
  { "name": "Armenia", "code": "AM", "alpha3": "ARM", "languages": ["Armenian"] },
  { "name": "Aruba", "code": "AW", "alpha3": "ABW", "languages": ["Dutch", "Papiamento"] },
  { "name": "Australia", "code": "AU", "alpha3": "AUS", "languages": ["English"] },
  { "name": "Austria", "code": "AT", "alpha3": "AUT", "languages": ["German"] },
  { "name": "Azerbaijan", "code": "AZ", "alpha3": "AZE", "languages": ["Azerbaijani"] },
  { "name": "Bahamas", "code": "BS", "alpha3": "BHS", "languages": ["English"] },
  { "name": "Bahrain", "code": "BH", "alpha3": "BHR", "languages": ["Arabic"] },
  { "name": "Bangladesh", "code": "BD", "alpha3": "BGD", "languages": ["Bengali"] },
  { "name": "Barbados", "code": "BB", "alpha3": "BRB", "languages": ["English"] },
  { "name": "Belarus", "code": "BY", "alpha3": "BLR", "languages": ["Belarusian", "Russian"] },
  { "name": "Belgium", "code": "BE", "alpha3": "BEL", "languages": ["Dutch", "French", "German"] },
  { "name": "Belize", "code": "BZ", "alpha3": "BLZ", "languages": ["English"] },
  { "name": "Benin", "code": "BJ", "alpha3": "BEN", "languages": ["French"] },
  { "name": "Bermuda", "code": "BM", "alpha3": "BMU", "languages": ["English"] },
  { "name": "Bhutan", "code": "BT", "alpha3": "BTN", "languages": ["Dzongkha"] },
  { "name": "Bolivia", "code": "BO", "alpha3": "BOL", "languages": ["Spanish", "Quechua", "Aymara"] },
  { "name": "Bosnia and Herzegovina", "code": "BA", "alpha3": "BIH", "languages": ["Bosnian", "Croatian", "Serbian"] },
  { "name": "Botswana", "code": "BW", "alpha3": "BWA", "languages": ["English", "Tswana"] },
  { "name": "Bouvet Island", "code": "BV", "alpha3": "BVT", "languages": ["None"] },
  { "name": "Brazil", "code": "BR", "alpha3": "BRA", "languages": ["Portuguese"] },
  { "name": "British Indian Ocean Territory", "code": "IO", "alpha3": "IOT", "languages": ["English"] },
  { "name": "Brunei Darussalam", "code": "BN", "alpha3": "BRN", "languages": ["Malay"] },
  { "name": "Bulgaria", "code": "BG", "alpha3": "BGR", "languages": ["Bulgarian"] },
  { "name": "Burkina Faso", "code": "BF", "alpha3": "BFA", "languages": ["French"] },
  { "name": "Burundi", "code": "BI", "alpha3": "BDI", "languages": ["Kirundi", "French", "English"] },
  { "name": "Cabo Verde", "code": "CV", "alpha3": "CPV", "languages": ["Portuguese", "Cape Verdean Creole"] },
  { "name": "Cambodia", "code": "KH", "alpha3": "KHM", "languages": ["Khmer"] },
  { "name": "Cameroon", "code": "CM", "alpha3": "CMR", "languages": ["English", "French"] },
  { "name": "Canada", "code": "CA", "alpha3": "CAN", "languages": ["English", "French"] },
  { "name": "Cayman Islands", "code": "KY", "alpha3": "CYM", "languages": ["English"] },
  { "name": "Central African Republic", "code": "CF", "alpha3": "CAF", "languages": ["French", "Sango"] },
  { "name": "Chad", "code": "TD", "alpha3": "TCD", "languages": ["French", "Arabic"] },
  { "name": "Chile", "code": "CL", "alpha3": "CHL", "languages": ["Spanish"] },
  { "name": "China", "code": "CN", "alpha3": "CHN", "languages": ["Mandarin"] },
  { "name": "Christmas Island", "code": "CX", "alpha3": "CXR", "languages": ["English"] },
  { "name": "Cocos (Keeling) Islands", "code": "CC", "alpha3": "CCK", "languages": ["English"] },
  { "name": "Colombia", "code": "CO", "alpha3": "COL", "languages": ["Spanish"] },
  { "name": "Comoros", "code": "KM", "alpha3": "COM", "languages": ["Comorian", "Arabic", "French"] },
  { "name": "Congo (Congo-Brazzaville)", "code": "CG", "alpha3": "COG", "languages": ["French"] },
  { "name": "Congo (Democratic Republic)", "code": "CD", "alpha3": "COD", "languages": ["French", "Swahili", "Lingala"] },
  { "name": "Cook Islands", "code": "CK", "alpha3": "COK", "languages": ["English", "Cook Islands Māori"] },
  { "name": "Costa Rica", "code": "CR", "alpha3": "CRI", "languages": ["Spanish"] },
  { "name": "Croatia", "code": "HR", "alpha3": "HRV", "languages": ["Croatian"] },
  { "name": "Cuba", "code": "CU", "alpha3": "CUB", "languages": ["Spanish"] },
  { "name": "Cyprus", "code": "CY", "alpha3": "CYP", "languages": ["Greek", "Turkish"] },
  { "name": "Czech Republic", "code": "CZ", "alpha3": "CZE", "languages": ["Czech"] },
  { "name": "Denmark", "code": "DK", "alpha3": "DNK", "languages": ["Danish"] },
  { "name": "Djibouti", "code": "DJ", "alpha3": "DJI", "languages": ["French", "Arabic"] },
  { "name": "Dominica", "code": "DM", "alpha3": "DMA", "languages": ["English"] },
  { "name": "Dominican Republic", "code": "DO", "alpha3": "DOM", "languages": ["Spanish"] },
  { "name": "Ecuador", "code": "EC", "alpha3": "ECU", "languages": ["Spanish"] },
  { "name": "Egypt", "code": "EG", "alpha3": "EGY", "languages": ["Arabic"] },
  { "name": "El Salvador", "code": "SV", "alpha3": "SLV", "languages": ["Spanish"] },
  { "name": "Equatorial Guinea", "code": "GQ", "alpha3": "GNQ", "languages": ["Spanish", "French", "Portuguese"] },
  { "name": "Eritrea", "code": "ER", "alpha3": "ERI", "languages": ["Tigrinya", "Arabic", "English"] },
  { "name": "Estonia", "code": "EE", "alpha3": "EST", "languages": ["Estonian"] },
  { "name": "Eswatini", "code": "SZ", "alpha3": "SWZ", "languages": ["English", "Swazi"] },
  { "name": "Ethiopia", "code": "ET", "alpha3": "ETH", "languages": ["Amharic"] },
  { "name": "Falkland Islands", "code": "FK", "alpha3": "FLK", "languages": ["English"] },
  { "name": "Faroe Islands", "code": "FO", "alpha3": "FRO", "languages": ["Faroese", "Danish"] },
  { "name": "Fiji", "code": "FJ", "alpha3": "FJI", "languages": ["English", "Fijian", "Hindi"] },
  { "name": "Finland", "code": "FI", "alpha3": "FIN", "languages": ["Finnish", "Swedish"] },
  { "name": "France", "code": "FR", "alpha3": "FRA", "languages": ["French"] },
  { "name": "French Guiana", "code": "GF", "alpha3": "GUF", "languages": ["French"] },
  { "name": "French Polynesia", "code": "PF", "alpha3": "PYF", "languages": ["French", "Tahitian"] },
  { "name": "French Southern Territories", "code": "TF", "alpha3": "ATF", "languages": ["French"] },
  { "name": "Gabon", "code": "GA", "alpha3": "GAB", "languages": ["French"] },
  { "name": "Gambia", "code": "GM", "alpha3": "GMB", "languages": ["English"] },
  { "name": "Georgia", "code": "GE", "alpha3": "GEO", "languages": ["Georgian"] },
  { "name": "Germany", "code": "DE", "alpha3": "DEU", "languages": ["German"] },
  { "name": "Ghana", "code": "GH", "alpha3": "GHA", "languages": ["English"] },
  { "name": "Gibraltar", "code": "GI", "alpha3": "GIB", "languages": ["English"] },
  { "name": "Greece", "code": "GR", "alpha3": "GRC", "languages": ["Greek"] },
  { "name": "Greenland", "code": "GL", "alpha3": "GRL", "languages": ["Greenlandic", "Danish"] },
  { "name": "Grenada", "code": "GD", "alpha3": "GRD", "languages": ["English"] },
  { "name": "Guadeloupe", "code": "GP", "alpha3": "GLP", "languages": ["French"] },
  { "name": "Guam", "code": "GU", "alpha3": "GUM", "languages": ["English", "Chamorro"] },
  { "name": "Guatemala", "code": "GT", "alpha3": "GTM", "languages": ["Spanish"] },
  { "name": "Guernsey", "code": "GG", "alpha3": "GGY", "languages": ["English"] },
  { "name": "Guinea", "code": "GN", "alpha3": "GIN", "languages": ["French"] },
  { "name": "Guinea-Bissau", "code": "GW", "alpha3": "GNB", "languages": ["Portuguese"] },
  { "name": "Guyana", "code": "GY", "alpha3": "GUY", "languages": ["English"] },
  { "name": "Haiti", "code": "HT", "alpha3": "HTI", "languages": ["French", "Haitian Creole"] },
  { "name": "Heard Island and McDonald Islands", "code": "HM", "alpha3": "HMD", "languages": ["None"] },
  { "name": "Holy See", "code": "VA", "alpha3": "VAT", "languages": ["Italian", "Latin"] },
  { "name": "Honduras", "code": "HN", "alpha3": "HND", "languages": ["Spanish"] },
  { "name": "Hong Kong", "code": "HK", "alpha3": "HKG", "languages": ["Cantonese", "English"] },
  { "name": "Hungary", "code": "HU", "alpha3": "HUN", "languages": ["Hungarian"] },
  { "name": "Iceland", "code": "IS", "alpha3": "ISL", "languages": ["Icelandic"] },
  { "name": "India", "code": "IN", "alpha3": "IND", "languages": ["Hindi", "English"] },
  { "name": "Indonesia", "code": "ID", "alpha3": "IDN", "languages": ["Indonesian"] },
  { "name": "Iran", "code": "IR", "alpha3": "IRN", "languages": ["Persian"] },
  { "name": "Iraq", "code": "IQ", "alpha3": "IRQ", "languages": ["Arabic", "Kurdish"] },
  { "name": "Ireland", "code": "IE", "alpha3": "IRL", "languages": ["English", "Irish"] },
  { "name": "Isle of Man", "code": "IM", "alpha3": "IMN", "languages": ["English"] },
  { "name": "Israel", "code": "IL", "alpha3": "ISR", "languages": ["Hebrew", "Arabic"] },
  { "name": "Italy", "code": "IT", "alpha3": "ITA", "languages": ["Italian"] },
  { "name": "Jamaica", "code": "JM", "alpha3": "JAM", "languages": ["English"] },
  { "name": "Japan", "code": "JP", "alpha3": "JPN", "languages": ["Japanese"] },
  { "name": "Jersey", "code": "JE", "alpha3": "JEY", "languages": ["English"] },
  { "name": "Jordan", "code": "JO", "alpha3": "JOR", "languages": ["Arabic"] },
  { "name": "Kazakhstan", "code": "KZ", "alpha3": "KAZ", "languages": ["Kazakh", "Russian"] },
  { "name": "Kenya", "code": "KE", "alpha3": "KEN", "languages": ["English", "Swahili"] },
  { "name": "Kiribati", "code": "KI", "alpha3": "KIR", "languages": ["English", "Gilbertese"] },
  { "name": "Kuwait", "code": "KW", "alpha3": "KWT", "languages": ["Arabic"] },
  { "name": "Kyrgyzstan", "code": "KG", "alpha3": "KGZ", "languages": ["Kyrgyz", "Russian"] },
  { "name": "Laos", "code": "LA", "alpha3": "LAO", "languages": ["Lao"] },
  { "name": "Latvia", "code": "LV", "alpha3": "LVA", "languages": ["Latvian"] },
  { "name": "Lebanon", "code": "LB", "alpha3": "LBN", "languages": ["Arabic"] },
  { "name": "Lesotho", "code": "LS", "alpha3": "LSO", "languages": ["English", "Sesotho"] },
  { "name": "Liberia", "code": "LR", "alpha3": "LBR", "languages": ["English"] },
  { "name": "Libya", "code": "LY", "alpha3": "LBY", "languages": ["Arabic"] },
  { "name": "Liechtenstein", "code": "LI", "alpha3": "LIE", "languages": ["German"] },
  { "name": "Lithuania", "code": "LT", "alpha3": "LTU", "languages": ["Lithuanian"] },
  { "name": "Luxembourg", "code": "LU", "alpha3": "LUX", "languages": ["Luxembourgish", "French", "German"] },
  { "name": "Macao", "code": "MO", "alpha3": "MAC", "languages": ["Cantonese", "Portuguese"] },
  { "name": "Madagascar", "code": "MG", "alpha3": "MDG", "languages": ["Malagasy", "French"] },
  { "name": "Malawi", "code": "MW", "alpha3": "MWI", "languages": ["English", "Chichewa"] },
  { "name": "Malaysia", "code": "MY", "alpha3": "MYS", "languages": ["Malay"] },
  { "name": "Maldives", "code": "MV", "alpha3": "MDV", "languages": ["Dhivehi"] },
  { "name": "Mali", "code": "ML", "alpha3": "MLI", "languages": ["French"] },
  { "name": "Malta", "code": "MT", "alpha3": "MLT", "languages": ["Maltese", "English"] },
  { "name": "Marshall Islands", "code": "MH", "alpha3": "MHL", "languages": ["English", "Marshallese"] },
  { "name": "Martinique", "code": "MQ", "alpha3": "MTQ", "languages": ["French"] },
  { "name": "Mauritania", "code": "MR", "alpha3": "MRT", "languages": ["Arabic"] },
  { "name": "Mauritius", "code": "MU", "alpha3": "MUS", "languages": ["English"] },
  { "name": "Mayotte", "code": "YT", "alpha3": "MYT", "languages": ["French"] },
  { "name": "Mexico", "code": "MX", "alpha3": "MEX", "languages": ["Spanish"] },
  { "name": "Micronesia", "code": "FM", "alpha3": "FSM", "languages": ["English"] },
  { "name": "Moldova", "code": "MD", "alpha3": "MDA", "languages": ["Romanian"] },
  { "name": "Monaco", "code": "MC", "alpha3": "MCO", "languages": ["French"] },
  { "name": "Mongolia", "code": "MN", "alpha3": "MNG", "languages": ["Mongolian"] },
  { "name": "Montenegro", "code": "ME", "alpha3": "MNE", "languages": ["Montenegrin"] },
  { "name": "Montserrat", "code": "MS", "alpha3": "MSR", "languages": ["English"] },
  { "name": "Morocco", "code": "MA", "alpha3": "MAR", "languages": ["Arabic", "Berber"] },
  { "name": "Mozambique", "code": "MZ", "alpha3": "MOZ", "languages": ["Portuguese"] },
  { "name": "Myanmar", "code": "MM", "alpha3": "MMR", "languages": ["Burmese"] },
  { "name": "Namibia", "code": "NA", "alpha3": "NAM", "languages": ["English"] },
  { "name": "Nauru", "code": "NR", "alpha3": "NRU", "languages": ["English", "Nauruan"] },
  { "name": "Nepal", "code": "NP", "alpha3": "NPL", "languages": ["Nepali"] },
  { "name": "Netherlands", "code": "NL", "alpha3": "NLD", "languages": ["Dutch"] },
  { "name": "New Zealand", "code": "NZ", "alpha3": "NZL", "languages": ["English", "Māori"] },
  { "name": "Nicaragua", "code": "NI", "alpha3": "NIC", "languages": ["Spanish"] },
  { "name": "Niger", "code": "NE", "alpha3": "NER", "languages": ["French"] },
  { "name": "Nigeria", "code": "NG", "alpha3": "NGA", "languages": ["English"] },
  { "name": "Niue", "code": "NU", "alpha3": "NIU", "languages": ["English", "Niuean"] },
  { "name": "Norfolk Island", "code": "NF", "alpha3": "NFK", "languages": ["English", "Norfuk"] },
  { "name": "North Macedonia", "code": "MK", "alpha3": "MKD", "languages": ["Macedonian"] },
  { "name": "Northern Mariana Islands", "code": "MP", "alpha3": "MNP", "languages": ["English", "Chamorro"] },
  { "name": "Norway", "code": "NO", "alpha3": "NOR", "languages": ["Norwegian"] },
  { "name": "Oman", "code": "OM", "alpha3": "OMN", "languages": ["Arabic"] },
  { "name": "Pakistan", "code": "PK", "alpha3": "PAK", "languages": ["Urdu", "English"] },
  { "name": "Palau", "code": "PW", "alpha3": "PLW", "languages": ["English", "Palauan"] },
  { "name": "Palestine State", "code": "PS", "alpha3": "PSE", "languages": ["Arabic"] },
  { "name": "Panama", "code": "PA", "alpha3": "PAN", "languages": ["Spanish"] },
  { "name": "Papua New Guinea", "code": "PG", "alpha3": "PNG", "languages": ["English", "Tok Pisin", "Hiri Motu"] },
  { "name": "Paraguay", "code": "PY", "alpha3": "PRY", "languages": ["Spanish", "Guarani"] },
  { "name": "Peru", "code": "PE", "alpha3": "PER", "languages": ["Spanish"] },
  { "name": "Philippines", "code": "PH", "alpha3": "PHL", "languages": ["Filipino", "English"] },
  { "name": "Pitcairn", "code": "PN", "alpha3": "PCN", "languages": ["English"] },
  { "name": "Poland", "code": "PL", "alpha3": "POL", "languages": ["Polish"] },
  { "name": "Portugal", "code": "PT", "alpha3": "PRT", "languages": ["Portuguese"] },
  { "name": "Puerto Rico", "code": "PR", "alpha3": "PRI", "languages": ["Spanish", "English"] },
  { "name": "Qatar", "code": "QA", "alpha3": "QAT", "languages": ["Arabic"] },
  { "name": "Republic of Korea", "code": "KR", "alpha3": "KOR", "languages": ["Korean"] },
  { "name": "Republic of Moldova", "code": "MD", "alpha3": "MDA", "languages": ["Romanian"] },
  { "name": "Réunion", "code": "RE", "alpha3": "REU", "languages": ["French"] },
  { "name": "Romania", "code": "RO", "alpha3": "ROU", "languages": ["Romanian"] },
  { "name": "Russian Federation", "code": "RU", "alpha3": "RUS", "languages": ["Russian"] },
  { "name": "Rwanda", "code": "RW", "alpha3": "RWA", "languages": ["Kinyarwanda", "English", "French"] },
  { "name": "Saint Barthélemy", "code": "BL", "alpha3": "BLM", "languages": ["French"] },
  { "name": "Saint Helena, Ascension and Tristan da Cunha", "code": "SH", "alpha3": "SHN", "languages": ["English"] },
  { "name": "Saint Kitts and Nevis", "code": "KN", "alpha3": "KNA", "languages": ["English"] },
  { "name": "Saint Lucia", "code": "LC", "alpha3": "LCA", "languages": ["English"] },
  { "name": "Saint Martin (French part)", "code": "MF", "alpha3": "MAF", "languages": ["French"] },
  { "name": "Saint Pierre and Miquelon", "code": "PM", "alpha3": "SPM", "languages": ["French"] },
  { "name": "Saint Vincent and the Grenadines", "code": "VC", "alpha3": "VCT", "languages": ["English"] },
  { "name": "Samoa", "code": "WS", "alpha3": "WSM", "languages": ["Samoan", "English"] },
  { "name": "San Marino", "code": "SM", "alpha3": "SMR", "languages": ["Italian"] },
  { "name": "Sao Tome and Principe", "code": "ST", "alpha3": "STP", "languages": ["Portuguese"] },
  { "name": "Saudi Arabia", "code": "SA", "alpha3": "SAU", "languages": ["Arabic"] },
  { "name": "Senegal", "code": "SN", "alpha3": "SEN", "languages": ["French"] },
  { "name": "Serbia", "code": "RS", "alpha3": "SRB", "languages": ["Serbian"] },
  { "name": "Seychelles", "code": "SC", "alpha3": "SYC", "languages": ["English", "French", "Seychellois Creole"] },
  { "name": "Sierra Leone", "code": "SL", "alpha3": "SLE", "languages": ["English"] },
  { "name": "Singapore", "code": "SG", "alpha3": "SGP", "languages": ["English", "Malay", "Mandarin", "Tamil"] },
  { "name": "Sint Maarten (Dutch part)", "code": "SX", "alpha3": "SXM", "languages": ["Dutch", "English"] },
  { "name": "Slovakia", "code": "SK", "alpha3": "SVK", "languages": ["Slovak"] },
  { "name": "Slovenia", "code": "SI", "alpha3": "SVN", "languages": ["Slovenian"] },
  { "name": "Solomon Islands", "code": "SB", "alpha3": "SLB", "languages": ["English"] },
  { "name": "Somalia", "code": "SO", "alpha3": "SOM", "languages": ["Somali", "Arabic"] },
  { "name": "South Africa", "code": "ZA", "alpha3": "ZAF", "languages": ["English", "Afrikaans", "Zulu", "Xhosa"] },
  { "name": "South Georgia and the South Sandwich Islands", "code": "GS", "alpha3": "SGS", "languages": ["English"] },
  { "name": "South Sudan", "code": "SS", "alpha3": "SSD", "languages": ["English"] },
  { "name": "Spain", "code": "ES", "alpha3": "ESP", "languages": ["Spanish"] },
  { "name": "Sri Lanka", "code": "LK", "alpha3": "LKA", "languages": ["Sinhala", "Tamil"] },
  { "name": "Sudan", "code": "SD", "alpha3": "SDN", "languages": ["Arabic", "English"] },
  { "name": "Suriname", "code": "SR", "alpha3": "SUR", "languages": ["Dutch"] },
  { "name": "Svalbard and Jan Mayen", "code": "SJ", "alpha3": "SJM", "languages": ["Norwegian"] },
  { "name": "Sweden", "code": "SE", "alpha3": "SWE", "languages": ["Swedish"] },
  { "name": "Switzerland", "code": "CH", "alpha3": "CHE", "languages": ["German", "French", "Italian", "Romansh"] },
  { "name": "Syrian Arab Republic", "code": "SY", "alpha3": "SYR", "languages": ["Arabic"] },
  { "name": "Taiwan", "code": "TW", "alpha3": "TWN", "languages": ["Mandarin"] },
  { "name": "Tajikistan", "code": "TJ", "alpha3": "TJK", "languages": ["Tajik"] },
  { "name": "Tanzania", "code": "TZ", "alpha3": "TZA", "languages": ["Swahili", "English"] },
  { "name": "Thailand", "code": "TH", "alpha3": "THA", "languages": ["Thai"] },
  { "name": "Timor-Leste", "code": "TL", "alpha3": "TLS", "languages": ["Portuguese", "Tetum"] },
  { "name": "Togo", "code": "TG", "alpha3": "TGO", "languages": ["French"] },
  { "name": "Tokelau", "code": "TK", "alpha3": "TKL", "languages": ["English", "Tokelauan"] },
  { "name": "Tonga", "code": "TO", "alpha3": "TON", "languages": ["Tongan", "English"] },
  { "name": "Trinidad and Tobago", "code": "TT", "alpha3": "TTO", "languages": ["English"] },
  { "name": "Tunisia", "code": "TN", "alpha3": "TUN", "languages": ["Arabic"] },
  { "name": "Turkey", "code": "TR", "alpha3": "TUR", "languages": ["Turkish"] },
  { "name": "Turkmenistan", "code": "TM", "alpha3": "TKM", "languages": ["Turkmen"] },
  { "name": "Tuvalu", "code": "TV", "alpha3": "TUV", "languages": ["English", "Tuvaluan"] },
  { "name": "Uganda", "code": "UG", "alpha3": "UGA", "languages": ["English", "Swahili"] },
  { "name": "Ukraine", "code": "UA", "alpha3": "UKR", "languages": ["Ukrainian"] },
  { "name": "United Arab Emirates", "code": "AE", "alpha3": "ARE", "languages": ["Arabic"] },
  { "name": "United Kingdom", "code": "GB", "alpha3": "GBR", "languages": ["English"] },
  { "name": "United States", "code": "US", "alpha3": "USA", "languages": ["English"] },
  { "name": "Uruguay", "code": "UY", "alpha3": "URY", "languages": ["Spanish"] },
  { "name": "Uzbekistan", "code": "UZ", "alpha3": "UZB", "languages": ["Uzbek"] },
  { "name": "Vanuatu", "code": "VU", "alpha3": "VUT", "languages": ["Bislama", "English", "French"] },
  { "name": "Venezuela", "code": "VE", "alpha3": "VEN", "languages": ["Spanish"] },
  { "name": "Viet Nam", "code": "VN", "alpha3": "VNM", "languages": ["Vietnamese"] },
  { "name": "Western Sahara", "code": "EH", "alpha3": "ESH", "languages": ["Arabic"] },
  { "name": "Yemen", "code": "YE", "alpha3": "YEM", "languages": ["Arabic"] },
  { "name": "Zambia", "code": "ZM", "alpha3": "ZMB", "languages": ["English"] },
  { "name": "Zimbabwe", "code": "ZW", "alpha3": "ZWE", "languages": ["English", "Shona", "Ndebele"] }
]